package com.example.githubexplorer.domain.entity

data class UserEntity(
    val login: String,
    val id: Long,
    val nodeId: String,
    val icon: String,
    val gravatarId: String?,
    val url: String,
    val htmlUrl: String,
    val followersUrl: String,
    val followingUrl: String,
    val gistsUrl: String,
    val starredUrl: String,
    val subscriptionsUrl: String,
    val organizationsUrl: String,
    val reposUrl: String,
    val eventsUrl: String,
    val receivedEventsUrl: String,
    val type: String,
    val siteAdmin: Boolean,
    val name: String?,
    val company: String?,
    val blog: String?,
    val location: String?,
    val email: String?,
    val notificationEmail: String?,
    val hireable: Boolean?,
    val bio: String?,
    val twitterUsername: String?,
    val publicRepos: Int?,
    val publicGists: Int?,
    val followers: Int?,
    val following: Int?,
    val createdAt: String?,
    val updatedAt: String?,
    val privateGists: Int?,
    val totalPrivateRepos: Int?,
    val ownedPrivateRepos: Int?,
    val diskUsage: Int?,
    val collaborators: Int?,
    val twoFactorAuthentication: Boolean?,
    val businessPlus: Boolean?,
    val ldapDn: String?,
    val plan: PlanEntity?
)

data class PlanEntity(
    val collaborators: Int,
    val name: String,
    val space: Int,
    val privateRepos: Int
)
